### PR TITLE
Make file/dir operations available as instance methods on File/Directory

### LINKED ISSUE #12: Open a FileId once, and re-use that for multiple operations on the file (existence, read, write, fileinfo, etc)

### LINKED ISSUE #57: DiskShare.getFile does not set fileId on returned File
Hi folks,

I just started digging into smbj and the whole smb topic on the technical level and encountered a behaviour that I would not have expected when it came down to using an input stream.

So I connected to a share and retrieved a File object via the getFile method of the DiskShare class. Unfortunately this File object could not be used to create an input stream as it would fail with a NullPointerException when calling read on the input stream.

If I get it correctly it seems that the fileId of the underlying File object was not set by getFile method although the fileId was available in the retrieved FileInfo. Is there a reason that the fileId from the FileInfo was not used in the created File object or is it just missing?

Regards,

Pernicies

### PR DESCRIPTION
**Pull request by pepijnve**
Fixes #12 by making file operations from DiskShare available as instance methods on DiskShare/File/Directory.
Also fixes #57.

### CODE REVIEW

File: src/main/java/com/hierynomus/mssmb2/messages/SMB2Flush.java [hunk 1]
```diff
@@ -32,8 +32,9 @@ public SMB2Flush() {
         super();
     }
 
-    public SMB2Flush(SMB2Dialect smbDialect) {
+    public SMB2Flush(SMB2Dialect smbDialect, SMB2FileId fileId) {
         super(24, smbDialect, SMB2MessageCommandCode.SMB2_FLUSH);
+        this.fileId = fileId;
```
Comment (hierynomus) [inline src/main/java/com/hierynomus/mssmb2/messages/SMB2Flush.java]: Do we need the setter still?

File: src/main/java/com/hierynomus/smbj/session/Session.java [hunk 2]
```diff
@@ -132,11 +136,11 @@ private void disconnectTree(TreeDisconnected disconnectEvent) {
 
     public void logoff() throws TransportException {
         logger.info("Logging off session {} from host {}", sessionId, connection.getRemoteHostname());
-        for (TreeConnect treeConnect : treeConnectTable.getOpenTreeConnects()) {
+        for (Share treeConnect : treeConnectTable.getOpenTreeConnects()) {
```
Comment (hierynomus) [inline src/main/java/com/hierynomus/smbj/session/Session.java]: rename to `share`

File: src/main/java/com/hierynomus/smbj/share/DiskEntry.java [hunk 3]
```diff
@@ -15,101 +15,93 @@
...
+
+    public SecurityDescriptor getSecurityInformation(Set<SecurityInformation> securityInfo) throws SMBApiException {
+        return share.getSecurityInfo(fileId, securityInfo);
+    }
+
+    public void rename(String newName)throws TransportException, SMBApiException {
+        this.rename(newName, false);
+    }
+
+    public void rename(String newName, boolean replaceIfExist)throws TransportException, SMBApiException {
```
Comment (hierynomus) [inline src/main/java/com/hierynomus/smbj/share/DiskEntry.java]: formatting, missing space (also below)

File: src/main/java/com/hierynomus/smbj/share/DiskShare.java [hunk 4]
```diff
@@ -105,56 +81,63 @@ public Directory openDirectory(
...
      */
-    public File openFile(String path, EnumSet<AccessMask> accessMask, SMB2CreateDisposition createDisposition) throws TransportException, SMBApiException {
-        logger.info("OpenFile {},{},{}", path, accessMask, createDisposition);
-
-        long accessMaskValue = toLong(accessMask);
-        SMB2FileId fileId = open(path, accessMaskValue, null, EnumSet.of(FILE_SHARE_READ), createDisposition, EnumSet.of(SMB2CreateOptions.FILE_NON_DIRECTORY_FILE));
-        // TODO
-        return new File(fileId, treeConnect, path, accessMaskValue);
+    public File openFile(String path, EnumSet<AccessMask> accessMask, SMB2CreateDisposition createDisposition) throws SMBApiException {
+        return (File) open(path, toLong(accessMask), EnumSet.of(FILE_ATTRIBUTE_DIRECTORY), EnumSet.noneOf(SMB2ShareAccess.class), createDisposition, EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE));
```
Comment (hierynomus) [inline src/main/java/com/hierynomus/smbj/share/DiskShare.java]: Are the passed options correct? They're the same as for the `openDirectory` call.

File: src/main/java/com/hierynomus/smbj/share/Share.java [hunk 5]
```diff
@@ -40,6 +40,8 @@
 
 public class Share implements AutoCloseable {
     private static final Logger logger = LoggerFactory.getLogger(Share.class);
+    private static final EnumSet<NtStatus> SUCCESS = EnumSet.of(NtStatus.STATUS_SUCCESS);
```
Comment (hierynomus) [inline src/main/java/com/hierynomus/smbj/share/Share.java]: Shouldn't these be `Set` also? ;)

File: src/main/java/com/hierynomus/mssmb2/messages/SMB2Flush.java (hunk 1 above)
Comment (pepijnve) [inline src/main/java/com/hierynomus/mssmb2/messages/SMB2Flush.java]: That's up to you. I don't think it's useful anymore, but I left it since it was already there.

File: src/main/java/com/hierynomus/smbj/share/DiskShare.java (hunk 4 above)
Comment (pepijnve) [inline src/main/java/com/hierynomus/smbj/share/DiskShare.java]: Nope that's wrong. Thanks for catching that.

File: src/main/java/com/hierynomus/smbj/share/Share.java (hunk 5 above)
Comment (pepijnve) [inline src/main/java/com/hierynomus/smbj/share/Share.java]: 😸 I changed a lot of fields and parameters from EnumSet to Set for added flexibility (for instance to allow using Guava ImmutableSet). Doesn't matter as much here since this is an internal constant. However you prefer.

**Comment by pepijnve** [comment]
Requested changes integrated

**Comment by Erates** [comment]
@hierynomus Any idea when a release will be available for this issue? I would like to rename files, but I can't depend on a non-released version.
