### PR TITLE
Correctly disable signing in case of guest/anonymous authentication

### LINKED ISSUE #196: Disabling signatures when guest/anonymous
We've had an ongoing discussion here around guest sessions: https://github.com/hierynomus/smbj/issues/184#issuecomment-329306762

The conclusion I've come to is that SMB does not allow for signing when the session is resolved to be a guest or anonymous: https://blogs.msdn.microsoft.com/openspecification/2017/05/26/smb-2-and-smb-3-security-in-windows-10-the-anatomy-of-signing-and-cryptographic-keys/
>
> To sign a message, the first two prerequisites are:
> • Existence of the signing key: SessionId field has a non-zero value, otherwise there would be no possible signing key. The exception is a guest or anonymous session, which does not have a signing key even there’s a SessionId.
> • Signing requirement: SessionId requires signing, i.e. its Session.SigningRequired is equal to TRUE as outlined previously.

Since from the perspective of an smbj user, I won't know that the session is guest or anonymous until the `Session` is returned to me. I've supported `SmbConfig.withSigningRequired` by checking if the returned Session is a guest or anonymous after it is returned, disabling signing if it is, and then reconnecting.

I feel like smbj could support this without forcing the reconnect from the user, perhaps by checking after it has completed the `SMB2_SESSION_SETUP` request and choosing not to calculate a secret key.  What do you think @hierynomus ?

### PR DESCRIPTION
**Pull request by hierynomus**
Fixes #196 and #184 

@Varsha-Nagarajan and @tosmun-r7 Can you verify whether this indeed fixes the problem?

### CODE REVIEW

File: src/main/java/com/hierynomus/smbj/session/Session.java [hunk 1]
```diff
@@ -72,6 +72,37 @@ public Session(Connection connection, AuthenticationContext auth, SMBEventBus bu
...
+        if (requireMessageSigning || connectionSigningRequired) {
+            signingRequired = true;
+        }
+
+        if (anonymous) {
+            // If the security subsystem indicates that the session was established by an anonymous user, Session.SigningRequired MUST be set to FALSE.
+            signingRequired = false;
+        }
+        if (guest && connection.getConfig().isSigningRequired()) {
+            throw new IllegalStateException("Cannot require message signing when authenticating with a guest account");
```
Comment (tosmun-r7) [inline src/main/java/com/hierynomus/smbj/session/Session.java]: Could we use a specific `SmbRuntimeException` for this?

Comment (hierynomus) [reply src/main/java/com/hierynomus/smbj/session/Session.java]: Yes, will do

**Comment by tosmun-r7** [comment]
Another question @hierynomus . Would it be possible to disable the signing requirement from the client but maintain the original connection? Since it's per-session. It would probably require the client config to be mutable though.

**Comment by hierynomus** [comment]
Not sure what you mean. The implementation now is entirely according to the spec. The Config object maintains the global RequireMessageSigning flag. So if that is set and you're guest-authenticating, it will throw an exception, otherwise your connection will succeed

**Comment by tosmun-r7** [comment]
Ah I see, so we'll treat all sessions on all connections produced by the client to require signing. Rather than a per-session basis.

**Comment by tosmun-r7** [comment]
Ah I see. If we request signing in the session (without knowing it's a guest ahead of time for example), and it ends up being guest, the spec states to close the connection. Got it.
> If the SMB2_SESSION_FLAG_IS_GUEST bit is set in the SessionFlags field of the SMB2 SESSION_SETUP Response and if Session.SigningRequired is TRUE, this indicates a SESSION_SETUP failure and the connection MUST be terminated.

**Comment by hierynomus** [comment]
Have you experimented with the implementation already @tosmun-r7 ? If so, I'll merge this

**Comment by tosmun-r7** [comment]
I'll test it out today and get back to you, thanks!

File: src/main/java/com/hierynomus/smbj/session/Session.java [hunk 2]
```diff
@@ -72,6 +72,37 @@ public Session(Connection connection, AuthenticationContext auth, SMBEventBus bu
...
+        if (requireMessageSigning || connectionSigningRequired) {
+            signingRequired = true;
+        }
+
+        if (anonymous) {
+            // If the security subsystem indicates that the session was established by an anonymous user, Session.SigningRequired MUST be set to FALSE.
+            signingRequired = false;
+        }
+        if (guest && connection.getConfig().isSigningRequired()) {
+            throw new SMBRuntimeException("Cannot require message signing when authenticating with a guest account");
```
Comment (tosmun-r7) [inline src/main/java/com/hierynomus/smbj/session/Session.java]: Could we use a really specific exception for this case that extends `SMBRuntimeException`? It will help with use cases where the client may wish to open a new connection without signing should they discover it's a guest account. i.e. `SMBGuestSigningViolationException` or something?

Comment (tosmun-r7) [reply src/main/java/com/hierynomus/smbj/session/Session.java]: Specifically the logic I'd like to capture is:
```java
Session session = null;
try {
   session = conn.authenticate(auth);
} catch (SMBGuestSigningViolationException e) {
   session.close();
   conn.close();
   conn = // No signing this time, and try again
}
```

The reason for this is I'd like to enforce signing in all cases *except* for guest, where it is not applicable.

**Comment by hierynomus** [comment]
@tosmun-r7 Anything more? Were you able to run it through some more tests?

**Comment by tosmun-r7** [comment]
@hierynomus Tested it just now and it works great, thanks! 🚢

**Comment by Varsha-Nagarajan** [comment]
@hierynomus sorry for the late reply. I tested it too and it works just great. I really appreciate it. Thanks :)
